#!/bin/sh
printf '__________                     .__                                        
\______   \ ____   ____   ____ |  |__ _____________   ____   ______ ______
 |    |  _// __ \ /    \_/ ___\|  |  \\____ \_  __ \_/ __ \ /  ___//  ___/
 |    |   \  ___/|   |  \  \___|   Y  \  |_> >  | \/\  ___/ \___ \ \___ \ 
 |______  /\___  >___|  /\___  >___|  /   __/|__|    \___  >____  >____  >
        \/     \/     \/     \/     \/|__|               \/     \/     \/ '
echo "  Bench:     ~/frappe-bench (Frappe develop, no site yet)"
echo "  Run it:    cd ~/frappe-bench && bench start"
echo "  Database:  none yet. This bench has no database server of its own."
echo "  Root:      sudo -i"
echo
